# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import videostream_pb2 as videostream__pb2


class VideoStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.stream_stream(
                '/VideoStream/Infer',
                request_serializer=videostream__pb2.Frame.SerializeToString,
                response_deserializer=videostream__pb2.Result.FromString,
                )


class VideoStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.stream_stream_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=videostream__pb2.Frame.FromString,
                    response_serializer=videostream__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VideoStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/VideoStream/Infer',
            videostream__pb2.Frame.SerializeToString,
            videostream__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
